spring:
  application:
    name: jackson-parse
  jackson:
    serialization:
      write-dates-as-timestamps: false
    default-property-inclusion: non_null
  mvc:
    contentnegotiation:
      favor-parameter: false
      favor-path-extension: false

server:
  port: 8080
